### ISSUE TITLE
Question about mimo in gnuradio 

### ISSUE THREAD

**Issue by Amberlan1001** [alick/gsoc2014-proposal#1]
Dear sir, I found you had implement some work with mimo by usrp N210, could you provide some sample examples ? And you attach the link of  your bachelor thesis report,while I could not open,could you give me the thesis name? Thanks in advance.

**Comment by alick** [comment]
Sorry the old link is broken now. I've put the thesis up again at a new place: http://people.tamu.edu/~alick/zhao2012bthesis.pdf

Please note that my implementation was on the gnuradio release several years ago and thus might work well with the current release. Besides, I did not test with N210 actually due to lack of devices at that time.

For further discussions you can contact me via my email (alick 9188 gmail)
